### ISSUE TITLE
Convert tiff to jpeg

### ISSUE THREAD

**Issue by raviy0807** [tdchaitanya/MMTOD#1]
Do we need to convert tiff images to jpeg? The dataset file "pascal VOC" take images in jpeg format.

Can you share your method to convert tiff to jpeg?

**Comment by raviy0807** [comment]
@tdchaitanya 
Could you please suggest and highlight on this issue?

**Comment by tdchaitanya** [comment]
In my case, I have used FLIR and KAIST datasets; both come with JPEG images. I think the conversion should be straight forward, can you try the approach mentioned [here](https://stackoverflow.com/a/28872806)?
